import * as ACTIONS from "../constants/actionTypes";

export default {
  [ACTIONS.CAMERA_LEFT]: 37,
  [ACTIONS.CAMERA_UP]: 38,
  [ACTIONS.CAMERA_RIGHT]: 39,
  [ACTIONS.CAMERA_DOWN]: 40,
  [ACTIONS.CAMERA_ROTATE_CLOCKWISE]: 69,
  [ACTIONS.CAMERA_ROTATE_COUNTER_CLOCKWISE]: 82
};
